---
- hosts: localhost
  become: yes
  tasks:
      - name: update repositories
        apt: update_cache=yes

      - name: install system tools
        apt: name= {{ item }} 
        with_items:
          - nano
          - net-tools
          - wine

      - name: install dev items available through apt
        apt: name= {{ item }} 
        with_items:
          - git
          - openjdk-11-jdk
          - python3
          - python3-pip
          - npm
          - docker
          - docker.io

      - name: install dev items available through snap
        snap:
          name:
            - scrcpy
            - intellij-idea-community
            - code

      - name: install entertainment items
        apt: name= {{ item }}
        with_items:
          - vlc