---
## Documentation on how to run the script exists here https://github.com/shereefsakr/ansible-dev-install

- hosts: all
  tasks:
      ## For testing purposes
      - name: "loop through list from a variable from all test"
        debug:
            msg: "An item: {{item}}"
        with_items:
            - 1
            - 2

- hosts: ubuntudevmachines

  vars:
    ## for chrome installation
    - chrome_apt_file: /etc/apt/sources.list.d/google-chrome.list
    ## for become plugin
    - ansible_become_exe: sudo
    - ansible_sudo_exe: sudo
    ## for vscode extension installation, currently not used yet
    - visual_studio_code_extensions_build: stable

  tasks:
      - name: install needed ppa repository
        apt_repository:
          repo: ppa:danielrichter2007/grub-customizer

      #- name: install cassandra apt repository
      #  apt_repository:
      #    repo: deb https://downloads.apache.org/cassandra/debian 311x main
  
      #- name: Add an Apt signing key for cassandra repository
      #  apt_key:
      #    url: https://downloads.apache.org/cassandra/KEYS
      #    state: present

      - name: update repositories
        apt: update_cache=yes

      - name: install system tools
        apt:
            name:
                - nano
                - gedit
                - net-tools
                - wine-stable
                - pavucontrol
                - grub-customizer
                - gnome-tweaks
            state: present
    
      ## For testing purposes
      - name: "loop through list from a variable"
        debug:
            msg: "An item: {{item}}"
        with_items:
            - 1
            - 2

      - name: install dev items available through apt
        apt:
            name:
                - git
                - openjdk-11-jdk
                - tomcat9
                - python3
                - python3-pip
                - npm
                - docker
                - docker.io
                - virtualbox
                #- cassandra
            state: present

      - name: install dev items available through snap
        snap:
          name:
            - scrcpy
            - intellij-idea-community
            - code
            - discord
            - zoom-client
          classic: yes

      #- name: install elastic search
      #  roles:
      #    - role: elastic.elasticsearch
      #  vars:
      #    es_version: 7.6.2

      - name: install entertainment items from apt
        apt:
            name:
                - vlc
                - openarena
      
      - name: install entertainment from snap
        snap:
            name:
            - spotify
            - vuze-vs
        
        
      - name: Does the Google apt file exist?
        command: test -f {{chrome_apt_file}}
        register: chrome_apt_exists
        ignore_errors: True
      - name: Add Google Chrome key
        shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        when: chrome_apt_exists.rc == 1
    
      - name: Add Google Chrome repo
        copy: content="deb http://dl.google.com/linux/chrome/deb/ stable main" dest={{apt_file}} owner=root group=root mode=644
        when: chrome_apt_exists.rc == 1
    
      - name: Update apt cache
        apt: update_cache=yes
        when: chrome_apt_exists.rc == 1
    
      - name: Install Google Chrome
        apt: pkg=google-chrome-stable state=present


- hosts: windevmachines
  tasks:
      ## For testing purposes
      - name: "loop through list from a variable from windevmachines test"
        debug:
            msg: "An item: {{item}}"
        with_items:
            - 1
            - 2

      - name: "test we can connect to the machine"
        win_ping:

      # - name: Install Telnet Client
      #   win_feature:
      #     name:
      #     - Telnet Client
      #     state: present

      - name: Install development items from chocolatey
        win_chocolatey:
          name: 
            - 7zip
            - windirstat
            - notepadplusplus
            - mremoteng
            - winmerge
            - pgadmin4
            - git
            - tortoisegit
            - openjdk8
            - intellijidea-community
            - apache-zookeeper
            - activemq
            - docker-desktop
          state: present

      - name: Stop ActiveMQ service and set it to manual
        win_service:
          name: ActiveMQ
          start_mode: manual
          state: stopped

      - name: Install postgres database
        win_chocolatey:
          name: postgresql11
          version: 11.5
          ##install_args: /Password:postgres
          state: present

      - name: Stop Postgres service and set it to manual
        win_service:
          name: postgresql-x64-11
          start_mode: manual
          state: stopped

      - name: Install tomcat
        win_chocolatey:
          name: tomcat
          version: 9.0.21
          state: present

      # - name: Stop Tomcat service and set it to manual
      #   win_service:
      #     name: Tomcat9
      #     start_mode: manual
      #     state: stopped

      - name: Install apache solr
        win_chocolatey:
          name: solr
          version: 8.1.1
          state: present

      - name: Install entertainment items from chocolatey
        win_chocolatey:
          name: 
            - vlc
            - spotify
            ##- itunes
            - kodi
            - scrcpy
            - ultravnc
            - virtualclonedrive
          state: present