---
- hosts: localhost
  become: yes
  tasks:
      - name: update repositories
        apt: update_cache=yes

      - name: install system tools
        apt: name= {{ item }} 
        with_items:
          - nano
          - net-tools

      - name: install dev items
        apt: name= {{ item }} 
        with_items:
          - git
          - openjdk-11-jdk
          - python3
          - python3-pip
          - npm

        state: present

      - name: install entertainment items
        apt: name= {{ item }}
        with_items:
          - vlc
        state: present